title: DJ Mixing Board Final Project
description: By Jacob Gonzalez and Jolene Gagliano

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
