title: DJ Mixing Board Final Project: By Jacob Gonzalez and Jolene Gagliano
description: By Jacob Gonzalez and Jolene Gagliano

remote_theme: qwtel/hydejack
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
